from generator import *
import random
class Nathan(Generator):
  nounslist = [
    "Table",
    "Chair",
    "Dog",
    "Cat",
    "Car",
    "Book",
    "Tree",
    "House",
    "Ball",
    "Phone",
    "Computer",
    "Flower",
    "River",
    "Mountain",
    "Sun",
    "Moon",
    "Star",
    "Cloud",
    "Bird",
    "Fish",
    "Elephant",
    "Lion",
    "Tiger",
    "Butterfly",
    "Turtle",
    "Pizza",
    "Guitar",
    "Drum",
    "Keyboard",
    "Microphone",
    "Telescope",
    "Camera",
    "Radio",
    "Bike",
    "Boat",
    "Plane",
    "Train",
    "Ship",
    "Wallet",
    "Backpack",
    "Key",
    "Knife",
    "Spoon",
    "Fork",
    "Plate",
    "Glass",
    "Cup",
    "Hat",
    "Shoe",
    "Bag",
    "Watch",
    "Clock",
    "Mirror",
    "Lamp",
    "Candle",
    "Pen",
    "Pencil",
    "Paper",
    "Bookshelf",
    "Camera",
    "Photo",
    "Ring",
    "Necklace",
    "Bracelet",
    "Earrings",
    "Guitar",
    "Violin",
    "Drum",
    "Paintbrush",
    "Sculpture",
    "Statue",
    "Toy",
    "Doll",
    "Teddy bear",
    "Puzzle",
    "Board game",
    "Robot",
    "Globe",
    "Map",
    "Telescope",
    "Microscope",
    "Feather",
    "Shell",
    "Rock",
    "Sand",
    "Seashell",
    "Coral",
    "Leaf",
    "Branch",
    "Acorn",
    "Pinecone",
    "Pineapple",
    "Banana",
    "Apple",
    "Orange",
    "Grape",
    "Watermelon",
    "Tomato",
    "Cucumber",
    "Carrot"
  ]

  adjectiveslist = [
    "Red",
    "Blue",
    "Green",
    "Yellow",
    "Small",
    "Big",
    "Happy",
    "Sad",
    "Angry",
    "Funny",
    "Serious",
    "Tall",
    "Short",
    "Fast",
    "Slow",
    "Beautiful",
    "Ugly",
    "Old",
    "Young",
    "Thin",
    "Thick",
    "Soft",
    "Hard",
    "Bright",
    "Dark",
    "Brave",
    "Cowardly",
    "Smart",
    "Stupid",
    "Clever",
    "Clumsy",
    "Kind",
    "Mean",
    "Polite",
    "Rude",
    "Friendly",
    "Hostile",
    "Gentle",
    "Harsh",
    "Calm",
    "Anxious",
    "Honest",
    "Dishonest",
    "Generous",
    "Stingy",
    "Patient",
    "Impatient",
    "Courageous",
    "Fearful",
    "Loud",
    "Quiet",
    "Energetic",
    "Lazy",
    "Silly",
    "Graceful",
    "Awkward",
    "Sincere",
    "Fake",
    "Modest",
    "Arrogant",
    "Creative",
    "Dull",
    "Adventurous",
    "Cautious",
    "Fierce",
    "Gentle",
    "Curious",
    "Indifferent",
    "Shy",
    "Confident",
    "Insecure",
    "Wise",
    "Foolish",
    "Careful",
    "Careless",
    "Cheerful",
    "Gloomy",
    "Unique",
    "Ordinary",
    "Delicious",
    "Disgusting",
    "Sunny",
    "Rainy",
    "Wind",
    "Breezy",
    "Cold",
    "Hot",
    "Fresh",
    "Stale",
    "Noisy",
    "Peaceful",
    "Busy",
    "Empty",
    "Wild",
    "Calm",
    "Clean",
    "Dirty",
    "Busy",
    "Free"
  ]  
  
  def getNoun(self):
    return random.choice(self.nounslist)
  
  def getAdjective(self):
    return random.choice(self.adjectiveslist)
  
  def getTemplate(self):
    return """
One day the {{noun}} went to see the {{noun}} at the park, and talked about {{noun}}s. They also bought a {{adjective}} {{adjective}} {{noun}} and a {{adjective}} {{noun}} from the {{noun}}, but that wasn't until after they ate the {{adjective}} {{noun}}.

The {{noun}} was shining brightly as the {{noun}} made their way to the park. {{adjective}} filled the air as they anticipated spending a {{adjective}} day in nature's embrace. As they arrived, the {{noun}} noticed the {{adjective}} beauty of the park, with its {{adjective}} {{noun}} and {{adjective}} {{noun}}s that adorned the landscape.

Eager to share their thoughts and experiences, the {{noun}} approached the {{noun}}, who was sitting on a bench, observing the surroundings. They sat down together, engaging in a {{adjective}} conversation about {{noun}}s. They discussed their favorite {{noun}}s, shared anecdotes, and exchanged {{adjective}} insights.

After their {{adjective}} conversation, they decided to explore the nearby food stalls. The aroma of {{adjective}} treats wafted through the air, enticing their senses. Among the array of options, a particular {{adjective}} {{adjective}} {{noun}} caught their attention. Its {{adjective}} smell and {{adjective}} presentation were too enticing to resist. They eagerly ordered it, savoring every {{adjective}} bite.

As they continued their culinary adventure, they stumbled upon a small vendor selling {{adjective}} handmade crafts. Their eyes lit up with {{adjective}} as they spotted a mesmerizing display of a {{adjective}} {{noun}}. Its {{adjective}} design and {{adjective}} colors immediately captivated their attention. Unable to resist its {{adjective}}, they decided to make it their own, knowing it would be a cherished addition to their collection.

Their exploration didn't end there. They also stumbled upon a stall showcasing a {{adjective}} piece of art—a {{adjective}} {{noun}}. Its {{adjective}} craftsmanship and {{adjective}} attention to detail left them in {{adjective}}. Enchanted by its {{adjective}}, they couldn't resist the urge to possess this {{noun}}, a true testament to the artist's {{noun}}.

After their {{adjective}} shopping experience, the {{noun}} and {{noun}} found a {{adjective}} spot under a {{adjective}} tree. They unwrapped the {{adjective}} {{noun}} they had purchased earlier. With each bite, they indulged in the {{adjective}} flavors that danced on their taste buds. The combination of {{noun}}s and the burst of flavors left them thoroughly satisfied.

As they savored the last morsels of their meal, they reflected on the {{adjective}} day they had shared. The park had been a {{noun}} for them, providing a respite from the {{adjective}} hustle and bustle. The bond they had forged over their shared interests had grown {{adjective}}, and their memories of this day would forever hold a {{adjective}} place in their hearts.

In conclusion, the day spent at the park was an {{adjective}} experience for the {{noun}}. From engaging in {{adjective}} conversations about {{noun}}s to indulging in {{adjective}} treats and acquiring {{adjective}} treasures, the day was filled with {{noun}} and discovery. It served as a reminder of the {{adjective}} pleasures that can be found in the company of a {{noun}}, the {{adjective}} of {{noun}}, and the {{adjective}} of exploring new experiences."""